CREATE DATABASE bookstore_0816;

CREATE TABLE bs_user(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	username VARCHAR(100) NOT NULL UNIQUE,
	PASSWORD VARCHAR(100),
	email VARCHAR(100)
);

CREATE TABLE bs_book(
	id INT(11) PRIMARY KEY AUTO_INCREMENT,
	title VARCHAR(100),
	author VARCHAR(100),
	price DOUBLE(11,2),
	sales INT(11),
	stock INT(11),
	img_path VARCHAR(120)
);